BZ/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('management.urls', namespace='management'))
]

management/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'management'

urlpatterns = [
    path('management_login/', auth_views.LoginView.as_view(), name='management_login'),
    path('management_logout/', auth_views.LogoutView.as_view(), name='management_logout'),
    path('console/', views.dashboard, name='dashboard')
    ]

ballotzen/models.py
from django.db import models

# Create your models here.

management/models.py
from django.db import models

# Create your models here.

ballotzen/views.py
from django.shortcuts import render

# Create your views here.

management/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def dashboard(request):
    return render(request, 'console/dashboard.html')

templates/console/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>




{% if request.user.is_authenticated %}
    <ul class="menu">
        <li>
            <a href="{% url "management:dashboard" %}">My dashboard</a>
            <a href="{% url "management:management_logout" %}">Logout</a>
        </li>
    </ul>
{% endif %}


<p>Welcome to the dashboard</p>





</body>
</html>